services:
  - name: my-backend
    type: web
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node backend/server.js
    envVars:
      - key: MONGO_URI
        sync: false  # Set this manually in Render Dashboard
      - key: JWT_SECRET
        sync: false  # Set this manually in Render Dashboard
        # Render auto-assigns a port, remove this if needed
